EXPORT_INCLUDES=$(shell echo *.h )
SOURCES=$(shell echo *.cpp)

MODE=CPP
TAGS_FILE=sgf_tools_simpleAPI-c++.tags

LINKED_LIBS=libKombilo libIOInterface libUtils

USE_OPENMP=YES
USE_BOOST=YES

TARGET_LIB=libSimpleAPI

include ../../makefile.include

