EXPORT_INCLUDES=$(shell echo *.h )
SOURCES=$(shell echo *.cpp)
FATAL_WARNINGS=NO

MODE=CPP
TAGS_FILE=sgf_tools_kombilo-c++.tags

LINKED_LIBS=

USE_OPENMP=YES
USE_BOOST=YES

TARGET_LIB=libKombilo

include ../../makefile.include

